### ISSUE TITLE
请教一下sharp是如何集成进去的？

### ISSUE THREAD

**Issue by hemengke1997** [wangyige0701/vscodeCustomExtension#64]
作者你好，我正在使用sharp在vscode中压缩图片使用
我看到你的项目中使用到了sharp，本地调试的使用，发现sharp并没有生效
请问怎么把sharp集成到vscode的扩展环境中呢
非常感谢！

**Comment by wangyige0701** [comment]
> 作者你好，我正在使用sharp在vscode中压缩图片使用 我看到你的项目中使用到了sharp，本地调试的使用，发现sharp并没有生效 请问怎么把sharp集成到vscode的扩展环境中呢 非常感谢！

你是正在开发vscode扩展并且希望使用sharp吗？sharp压缩图片的功能是单独的`.node`二进制文件完成的，这些文件我没弄错的话是通过c++开发的，而sharp的npm包是通过script脚本在被下载时触发一个下载命令将二进制文件下载到node_modules文件夹下进行调用。

具体你可以去node_modules下的sharp目录里查看，它的脚本命令里有个install命令，其中就是下载二进制文件时所需要调用的文件（`prebuild-install/bin`,`sharp/install/dll-copy`,`sharp/install/libvips`）。如果你希望在生产环境中也使用sharp，第一个方法是直接把node_modules一起打包，这样会造成打包体积过大；第二个方法是单独将sharp下载二进制文件的js文件也打包到正式环境里，正式环境版本更新时触发脚本并下载。

我开发的这个扩展里使用的打包工具是rollup，具体的实现思路是，新建三个入口文件，例如有一个文件是`prebuild-install/bin`，那么就在一个单独的文件里写上`import "prebuild-install/bin"`，在rollup中单独写一个配置项以此文件为入口把所有需要的依赖全部打包，最终正式环境里会通过spawnSync进行调用手动下载二进制文件到正式环境中。

其中有几个注意点，第一是使用spawnSync是因为三个脚本一定要按序执行，因为其中有个脚本是把下载好的文件拷贝到别的地方；第二是要注意打包后的这三个文件存放路径，不能放在项目根目录下，否则下载的二进制文件会被塞到父目录里，因为sharp中下载存放路径写死了是要向上一层的。

不知道我表述的清不清楚，如果还有问题可以继续询问。

**Comment by hemengke1997** [comment]
你好，感谢回复。
昨天直到现在，我研究后发现了或许更简单的做法：**严格区分依赖安装类型**

把vscode环境中使用到的依赖，安装到 `dependencies` 中，而非vscode环境中的依赖，比如webview中使用到web相关依赖，安装到 `devDependencies` 中。

同时，把 `.vscodeignore` 中的 node_modules 给删掉，保持vscode打包的时候把 node_modules 带上。很重要的是，打包结果并不会引入所有的 node_modules，因为 vscode 内部做了优化，只会引入 prod 的依赖

这样做的话，可以直接在vscode环境中使用 sharp 或其他的二进制bin包了

以上的结论并不一定正确，是我今天实践后总结的。如果有不对的地方，请指正！

**Comment by wangyige0701** [comment]
听起来确实可行，不过我觉得有几点需要考虑一下。

第一是sharp下载的二进制文件相较项目文件大小会非常大，windows的文件记得是有70m的，如果需要上传到扩展市场并且下载的话中间会耗费更多的时间和流量，这也是我去研究正式环境手动下载的原因。

第二是sharp包是需要根据操作系统下载不同包的，如果只从开发环境进行二进制文件的上传的话，会造成有些用户可能使用不起来。当然，这一点的影响会根据你的实际情况来区分，如果你的扩展有特定用户并且能指定系统那么影响并不会很大。

**Comment by hemengke1997** [comment]
谢谢你的建议，我确实没有考虑到用户平台的问题，我使用的macos，sharp的体积并不大。

我结合你的想法，重新设计了方案，node_modules添加到忽略列表中，在用户启动插件的时候，修改插件根目录的 `package.json` 文件，使其依赖有且仅有 `sharp`，结果大致是：

```json
...其他字段

dependencies: { sharp: "xxx" },
devDependencies: {}
```
然后执行安装依赖命令：
```js
execa('npm', ['install'])
```

最后用户的本地就有了依赖，且只是sharp相关的，不出意外的话，sharp应该也是安装用户对应平台的binary（未经测试，我本地是只有 `sharp-darwin-arm64v8.node` 

然后在项目中只能使用 `require` 或者 `await import` 的方式引入，因为 `sharp` 是懒生成的。

如果你有建议或意见，请随意指出！

**Comment by wangyige0701** [comment]
这个方案我觉得有一个问题需要考虑，如果不是有特定用户，那么不能以每位用户系统中都有npm工具为前提去启动命令，甚至如果有用户安装了npm但是没有添加到环境变量中，这个命令同样会执行失败。
